<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        DB::table('users')->insert([
            'name' => 'Admin',
            'email' => 'admin@admin.com',
            'contact_no' => 'https://web.facebook.com/?_rdc=1&_rdr', // You can set this to the admin's contact number if needed
            'website_url' => null, // Set to null or a website URL if needed
            'status' => true,
            'password' => Hash::make('password'), // Hash the password for security
            'type'=>1,
            'remember_token' => null, // Automatically generated by Laravel when logging in
            'created_at' => now(),
            'updated_at' => now(),
        ]);
    }
}
